/* Drop ALL Tables; */

USE Shopaholic;

DROP TABLE ReviewsTextualContext;
DROP TABLE Reviews;
DROP TABLE MerchantOrders;
DROP TABLE Orders;
DROP TABLE CartProducts;
DROP TABLE Cart;
DROP TABLE MerchantProducts;
DROP TABLE Products;
DROP TABLE Merchants;
DROP TABLE MemberUsersFriends;
DROP TABLE MemberUsers;
DROP TABLE Admin;

/* CREATE DATABASE Shopaholic; */

CREATE TABLE Admin(
	AID CHAR(1) PRIMARY KEY NOT NULL UNIQUE,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    UserName VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL
);

CREATE TABLE MemberUsers(
	UID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,  
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL,
    ShippingAddress VARCHAR(50) DEFAULT '',    
    UserName VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL,
    JoinDate DATE
);

CREATE TABLE MemberUsersFriends(
	UID INT(5) NOT NULL,
    FUID INT(5) NOT NULL,
    PRIMARY KEY(UID, FUID),
    FOREIGN KEY(UID) REFERENCES MemberUsers(UID) ON DELETE CASCADE
);


CREATE TABLE Merchants(
	MID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    UserName VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL,
    JoinDate DATE
);

CREATE TABLE Products(
	PID INT(5) PRIMARY KEY AUTO_INCREMENT UNIQUE, 
    ProductName CHAR(25) NOT NULL,
	Price FLOAT NOT NULL,
    ProductType VARCHAR(25) NOT NULL,
    ProductDescription VARCHAR(50),
    Img VARCHAR(500) NOT NULL
);

CREATE TABLE MerchantProducts(
	MID INT(5) NOT NULL,
    PID INT(5) NOT NULL,
    PRIMARY KEY(MID, PID),
    FOREIGN KEY(MID) REFERENCES Merchants(MID) ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

CREATE TABLE Reviews (
	RID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    PID INT(5) NOT NULL, 
    Author VARCHAR(25) NOT NULL,
    ProductName VARCHAR(25) NOT NULL,
    ReviewDescription VARCHAR(50),
    Stars INTEGER, CHECK (Stars >= 1 AND Stars <= 5),
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

CREATE TABLE ReviewsTextualContext(
	RID INT(5) NOT NULL AUTO_INCREMENT,
    ContextType VARCHAR(25) NOT NULL,
    PRIMARY KEY(RID, ContextType),
    FOREIGN KEY(RID) REFERENCES Reviews(RID) ON DELETE CASCADE
);

CREATE TABLE Cart(
	CID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    UID INT(5) NOT NULL,
    FOREIGN KEY(UID) REFERENCES MemberUsers(UID) ON DELETE CASCADE
);


CREATE TABLE Orders(
	OID INT(5) NOT NULL AUTO_INCREMENT UNIQUE,
    CID INT(5) NOT NULL,
    ProductName CHAR(25) NOT NULL,
    OrderDate DATE,
    PRIMARY KEY(OID, ProductName),
    FOREIGN KEY(CID) REFERENCES Cart(CID) ON DELETE CASCADE
);

CREATE TABLE MerchantOrders(
	MID INT(5) NOT NULL,
    OID INT(5) NOT NULL,
    PRIMARY KEY(MID, OID),
    FOREIGN KEY(MID) REFERENCES Merchants(MID) ON DELETE CASCADE,
    FOREIGN KEY(OID) REFERENCES Orders(OID) ON DELETE CASCADE
);

CREATE TABLE CartProducts(
	CID INT(5) NOT NULL,
	PID INT(5) NOT NULL,
    PRIMARY KEY(PID),
    ProductName CHAR(25) NOT NULL,
    ProductType VARCHAR(25) NOT NULL,
    Quantity INTEGER NOT NULL,
    TotalPrice FLOAT NOT NULL,
    Img VARCHAR(500) NOT NULL,
    FOREIGN KEY(CID) REFERENCES Cart(CID) ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

