

/* CREATE DATABASE Shopaholic; */
USE Shopaholic;

CREATE TABLE Admin(
	AID CHAR(1) PRIMARY KEY NOT NULL UNIQUE,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    UserName VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL
);

CREATE TABLE MemberUsers(
	UID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,  
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL,
    ShippingAddress VARCHAR(50) DEFAULT '',    
    UserName VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL,
    JoinDate DATE
);

CREATE TABLE MemberUsersFriends(
	UID INT(5) NOT NULL,
    FUID INT(5) NOT NULL,
    PRIMARY KEY(UID, FUID),
    FOREIGN KEY(UID) REFERENCES MemberUsers(UID) ON DELETE CASCADE
);


CREATE TABLE Merchants(
	MID INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    UserName VARCHAR(25) NOT NULL,
    Email VARCHAR(25) NOT NULL,
	UserPassword VARCHAR(25) NOT NULL,
    JoinDate DATE
);

CREATE TABLE Products(
	PID INT(7) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    ProductName CHAR(25) NOT NULL,
	Price INTEGER NOT NULL,
    ProductType VARCHAR(25),
    ProductDescription VARCHAR(50),
     Img VARCHAR(500),
    Availability BOOLEAN,
    ProductStatus VARCHAR(25)
);

CREATE TABLE MerchantProducts(
	MID INT(3) NOT NULL,
    PID INT(7) NOT NULL,
    PRIMARY KEY(MID, PID),
    FOREIGN KEY(MID) REFERENCES Merchants(MID) ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

CREATE TABLE Reviews (
	RID INT(8) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    PID INT(7) NOT NULL, 
    Author VARCHAR(25) NOT NULL,
    ProductName VARCHAR(25) NOT NULL,
    ReviewDescription VARCHAR(50),
    Stars INTEGER, CHECK (Stars >= 1 AND Stars <= 5),
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

CREATE TABLE ReviewsTextualContext(
	RID INT(8) NOT NULL AUTO_INCREMENT,
    ContextType VARCHAR(25) NOT NULL,
    PRIMARY KEY(RID, ContextType),
    FOREIGN KEY(RID) REFERENCES Reviews(RID) ON DELETE CASCADE
);

CREATE TABLE Cart(
	CID INT(2) PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    UID INT(5) NOT NULL,
    Quantity INTEGER,
    TotalPrice INTEGER,
    FOREIGN KEY(UID) REFERENCES MemberUsers(UID) ON DELETE CASCADE
);


CREATE TABLE Orders(
	OID INT(9) NOT NULL AUTO_INCREMENT UNIQUE,
    CID INT(2) NOT NULL,
    ProductName INT(25) NOT NULL,
    OrderDate DATE,
    PRIMARY KEY(OID, ProductName),
    FOREIGN KEY(CID) REFERENCES Cart(CID) ON DELETE CASCADE
);

CREATE TABLE MerchantOrders(
	MID INT(3) NOT NULL,
    OID INT(9) NOT NULL,
    PRIMARY KEY(MID, OID),
    FOREIGN KEY(MID) REFERENCES Merchants(MID) ON DELETE CASCADE,
    FOREIGN KEY(OID) REFERENCES Orders(OID) ON DELETE CASCADE
);

CREATE TABLE CartProducts(
	CID INT(2) NOT NULL AUTO_INCREMENT,
	PID INT(7) NOT NULL,
    ProductName VARCHAR(25),
    PRIMARY KEY(CID, PID),
    FOREIGN KEY(CID) REFERENCES Cart(CID) ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCES Products(PID) ON DELETE CASCADE
);

