/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-23 22:16:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createaccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<meta name = \"viewport\" \n");
      out.write("	content = \"width = device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"author\" content = \"\" />\n");
      out.write("\n");
      out.write("<!-- Favicon -->\n");
      out.write("<link rel = \"icon\" type = \"image/x-icon\" href = \"asset/favicon.ico\"/>\n");
      out.write("<!-- Font Awesome icons (free version) -->\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.15.4/js/all.js\" crossorigin = \"anonymous\"></script>\n");
      out.write("<!--Google fonts  -->\n");
      out.write("<link href = \"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type = text/css />\n");
      out.write("<!-- Core theme CSS (bootstrap) -->	\n");
      out.write("<link href = \"style.css\" rel=\"stylesheet\"/>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Signing Up</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class = 'main'>\n");
      out.write("		<section class = \"sign-up\">\n");
      out.write("			<div class = \"container\">\n");
      out.write("				<div class = \"signup-content\">\n");
      out.write("					<div class=\"signup-form\">\n");
      out.write("						<h2 class = 'form-title'>Sign Up</h2>\n");
      out.write("					\n");
      out.write("						<form method = \"POST\" action = \"SignUpServlet\" class = \"register-form\" id = \"signup-form\">\n");
      out.write("								\n");
      out.write("							<!-- First Name -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<label for=\"FirstName\">\n");
      out.write("									<i class=\"\"></i></label>\n");
      out.write("									<input type=\"text\" name=\"FirstName\" id=\"FirstName\"\n");
      out.write("									placeholder = \"FirstName\"/>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<!-- Last Name -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<label for=\"LastName\">\n");
      out.write("									<i class=\"\"></i></label>\n");
      out.write("									<input type=\"text\" name=\"LastName\" id=\"LastName\"\n");
      out.write("									placeholder = \"LastName\"/>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<!-- User Name -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<label for=\"UserName\">\n");
      out.write("									<i class=\"\"></i></label>\n");
      out.write("									<input type=\"text\" name=\"UserName\" id=\"UserName\"\n");
      out.write("									placeholder = \"Username\"/>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							");
 String UserName = (String) request.getAttribute("UserName");
							   request.getSession().setAttribute("UserName", UserName); 
							
      out.write("\n");
      out.write("							\n");
      out.write("							<!-- Email -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<label for=\"email\">\n");
      out.write("									<i class=\"\"></i></label>\n");
      out.write("									<input type=\"email\" name=\"email\" id=\"email\"\n");
      out.write("									placeholder = \"email\"/>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<!-- Password -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<label for=\"password\">\n");
      out.write("									<i class=\"\"></i></label>\n");
      out.write("									<input type=\"password\" name=\"password\" id=\"password\"\n");
      out.write("									placeholder = \"password\"/>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<!-- User type -->\n");
      out.write("							<div class =\"form-group\">\n");
      out.write("								<select name=\"UserType\">\n");
      out.write("										<option value=\"User\">User</option>\n");
      out.write("										<option value=\"Merchant\">Merchant</option>\n");
      out.write("										<option value=\"Admin\">Admin</option>\n");
      out.write("								</select>\n");
      out.write("							</div>\n");
      out.write("					\n");
      out.write("							\n");
      out.write("							<!-- Submit button -->\n");
      out.write("							<div class=\"form-group form-button\">\n");
      out.write("								<input type=\"submit\" name = 'signin' id=\"signin\" class =\"form-submit\" value =\"Sign Up\" />\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("					<div class = \"signup-image\">\n");
      out.write("						<figure>\n");
      out.write("							<img src = \"images/signup-image.jpg\" alt=\"sign up image\">\n");
      out.write("						</figure>\n");
      out.write("						<a href = \"login.jsp\" class = \"signup-image-link\">Already a member? Log In</a>\n");
      out.write("					\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("	</div>\n");
      out.write("		\n");
      out.write("	<!-- <div align=\"center\">\n");
      out.write("		<h1>Please enter your info below to create an account.</h1>\n");
      out.write("		<form action=\"SignUpServlet\" method=\"POST\">\n");
      out.write("			<table style=\"with: 80%\">\n");
      out.write("				<tr>\n");
      out.write("					<td>ID</td>\n");
      out.write("					<td><input type=\"text\" name=\"ID\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>First Name</td>\n");
      out.write("					<td><input type=\"text\" name=\"FirstName\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>Last Name</td>\n");
      out.write("					<td><input type=\"text\" name=\"LastName\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>User Name</td>\n");
      out.write("					<td><input type=\"text\" name=\"UserName\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>UserPassword</td>\n");
      out.write("					<td><input type=\"password\" name=\"UserPassword\" /></td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td>Select UserType</td>\n");
      out.write("					<td><select name=\"UserType\">\n");
      out.write("							<option value=\"User\">User</option>\n");
      out.write("							<option value=\"Merchant\">Merchant</option>\n");
      out.write("					</select>\n");
      out.write("			</table>\n");
      out.write("			<h1></h1>\n");
      out.write("			<input type=\"submit\" value=\"Create\"/>\n");
      out.write("		</form>\n");
      out.write("	</div> -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
